### ISSUE TITLE
inconsistent indentation, semi-colons

### ISSUE THREAD

**Issue by aric87** [bpcoxjr/countries-and-capitals#1]
https://github.com/bpcoxjr/countries-and-capitals/blob/master/tests/geonamesSpec.js#L11

here you don't have a semi-colon, other var declarations you do. Not required, but consistency is: 
https://github.com/bpcoxjr/countries-and-capitals/blob/master/tests/geonamesSpec.js#L19

**Comment by bpcoxjr** [comment]
Fixed.
